
export const REGISTERATION_REQUEST = 'REGISTERATION_REQUEST';
export const TEAM_REGISTER_REQUEST = "TEAM_REGISTER_REQUEST";


export const REGISTERATION_SUBMITTING = 'REGISTERATION_SUBMITTING';

export const REGISTERATION_SUCCESS = 'REGISTERATION_SUCCESS';
export const REGISTERATION_FAIL = 'REGISTERATION_FAIL';


