// player registration actions
export const PLAYER_REGISTERATION_REQUEST = 'REGISTERATION_REQUEST';
export const PLAYER_REGISTER_SUBMITTING = 'PLAYER_REGISTER_SUBMITTING';
export const PLAYER_REGISTER_SUCCESS = 'PLAYER_REGISTER_SUCCESS';
export const PLAYER_REGISTER_FAIL = 'PLAYER_REGISTER_FAIL';


//player lsit actions
export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST';
export const PLAYER_LIST_SUCCESS = 'PLAYER_LIST_SUCCESS';
export const PLAYER_LIST_FAIL = 'PLAYER_LIST_FAIL';

// get player

export const PLAYER_REQUEST = 'PLAYER_REQUEST';
export const PLAYER_SUCCESS = 'PLAYER_SUCCESS';
export const PLAYER_FAIL = 'PLAYER_FAIL';




//player edit actions

export const PLAYER_EDIT_REQUEST = 'PLAYER_EDIT_REQUEST';
export const PLAYER_EDIT_SUCCESS = 'PLAYER_EDIT_SUCCESS';
export const PLAYER_EDIT_FAIL = 'PLAYER_EDIT_FAIL';

//player del actions
export const PLAYER_DEL_REQUEST = 'PLAYER_EDIT_REQUEST';
export const PLAYER_DEL_SUCCESS = 'PLAYER_DEL_SUCCESS';
export const PLAYER_DEL_FAIL = 'PLAYER_DEL_FAIL';

// team registration actions
export const TEAM_REGISTERATION_REQUEST = 'TEAM_REGISTER_REQUEST';
export const TEAM_REGISTER_SUBMITTING = 'TEAM_REGISTER_SUBMITTING';
export const TEAM_REGISTER_SUCCESS = 'TEAM_REGISTER_SUCCESS';
export const TEAM_REGISTER_FAIL = 'TEAM_REGISTER_FAIL';
